language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
virtualenv:
  system_site_packages: true

before_install:
  - pip install -U pip

install:
  - travis_wait travis_retry pip install scikit-learn

script: nosetests
